# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(max_length=200)),
                ('property_owner', models.CharField(max_length=200)),
                ('property_address', models.CharField(max_length=200)),
                ('property_state', models.CharField(max_length=200)),
                ('property_city', models.CharField(max_length=200)),
                ('property_bid', models.IntegerField(default=0)),
                ('property_date', models.DateTimeField()),
                ('property_lat', models.FloatField()),
                ('property_lng', models.FloatField()),
            ],
        ),
    ]
