# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lienMapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_bid',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_lng',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_state',
            new_name='state',
        ),
    ]
