# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lienMapper', '0002_auto_20170923_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='code',
            new_name='owners',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='prop_id',
        ),
    ]
